CREATE TABLE AD
(
    ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(256) default NULL ,
    URL VARCHAR(512) default NULL ,
    IMAGE VARCHAR(256) default NULL ,
    GMT_START BIGINT,
    GMT_END BIGINT,
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    STATUS INT,
    POS VARCHAR(10) NOT NULL
);